#    This file is part of Silk
#    (c) Edward Mills 2016-2017
#    edwardvmills@gmail.com
#
#    NURBS Surface modeling tools focused on low degree and seam continuity (FreeCAD Workbench) 
#
#    Silk is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

import FreeCAD, Part, math
from FreeCAD import Base
from FreeCAD import Gui
import ArachNURBS as AN

# Locate Workbench Directory
import os, Silk_dummy
path_Silk = os.path.dirname(Silk_dummy.__file__)
path_Silk_icons =  os.path.join( path_Silk, 'Resources', 'Icons')

class SubGrid63_2Surf64():
	def Activated(self):
		sel=Gui.Selection.getSelection()
		Surf_0=Gui.Selection.getSelection()[0] 
		Surf_1=Gui.Selection.getSelection()[1]

		a=FreeCAD.ActiveDocument.addObject("Part::FeaturePython","SubGrid63_2Surf64")
		AN.SubGrid63_2Surf64(a,Surf_0,Surf_1)
		a.ViewObject.Proxy=0 # just set it to something different from None (this assignment is needed to run an internal notification)
		a.ViewObject.LineWidth = 1.00
		a.ViewObject.LineColor = (1.00,0.67,0.00)
		a.ViewObject.PointSize = 2.00
		a.ViewObject.PointColor = (1.00,1.00,0.00)
		FreeCAD.ActiveDocument.recompute()

	def GetResources(self):
		return {'Pixmap' :  path_Silk_icons + '/SubGrid63_2Surf64.svg',
				'MenuText': 'SubGrid63_2Surf64',
				'ToolTip': 'Create a SubGrid63 subgrid from two CubicSurface64 surfaces. \n Select two CubicSurface64 objects that share a corner. \n \n â€¢ Input for ControlGridNStar66 to blend three or more \n   blended edges meeting at a corner '}

Gui.addCommand('SubGrid63_2Surf64', SubGrid63_2Surf64())
